version: 2

updates:

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
