#!/bin/bash


BINARY_PREFIX="barcomic"
MAJOR="1"
MINOR="0"
PATCH="3"
PROJECT_VERSION="v$MAJOR.$MINOR.$PATCH"
COMMIT_HASH=$(git rev-parse HEAD)

export BINARY_PREFIX
export PROJECT_VERSION
export COMMIT_HASH
