name: Push and Pull

on:
  push:
    branches:
      - "main"

jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: make install_golang_deps

      - name: Install robotgo dependencies
        run: make install_linux_deps

      - name: Run unit tests
        run: make test

  build_and_test_darwin:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: make install_golang_deps

      - name: Run unit tests
        run: make test
