name: Push and Pull

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
          cache: true

      - name: Check Go version
        run: go version

      - name: Install golang dependencies
        run: go get .

      - name: Install robotgo dependencies
        run: make install_linux_deps
        
      - name: Run unit tests
        run: make test
